format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_commit\
$line_break\
$python\
$character"""

[character]
success_symbol = "[❯](black)"
error_symbol = "[❯](black)"
vicmd_symbol = "[❯](black)"

[git_branch]
format = "[$branch]($style)"
symbol = " "
style = "black"

[git_commit]
format = "[$hash]($style) "
style = "white bold"
commit_hash_length = 7
tag_symbol = " 🏷 "

[git_status]
format = "[[(* $conflicted$untracked$staged$deleted$renamed$modified)](red) ( $ahead_behind$stashed)]($style)"
style = "red"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
staged = "+"
renamed = "»"
modified = "~"
deleted = "✘"
stashed = "≡"
untracked = "?"

[directory]
style = "blue bold"
read_only = "🔒"
truncation_length = 2
